name: ScriptCommands
version: 1.0.0
main: me.gordey9992.scriptcommands.ScriptCommands
api-version: "1.21"
authors: [gordey9992, DeepSeek]
description: Динамические команды из Java скриптов для Purpur 1.21.11
website: https://github.com/gordey9992/ScriptCommands

commands:
  scriptreload:
    description: Перезагрузить скрипты
    usage: /scriptreload
    permission: scriptcommands.reload
    aliases: [sr, scriptsreload, sreload]
  
  screload:
    description: Полная перезагрузка плагина
    usage: /screload
    permission: scriptcommands.reload-all
    aliases: [scr]
  
  scupdateyes:
    description: Установить новую версию
    usage: /scupdateyes
    permission: scriptcommands.update.accept
  
  scupdateno:
    description: Пропустить обновление
    usage: /scupdateno
    permission: scriptcommands.update.msg
  
  script:
    description: Управление плагином
    usage: /script update
    permission: scriptcommands.update.msg

permissions:
  scriptcommands.reload:
    description: Перезагрузка скриптов
    default: op
  scriptcommands.reload-all:
    description: Полная перезагрузка
    default: op
  scriptcommands.update.msg:
    description: Получать уведомления об обновлениях
    default: op
  scriptcommands.update.accept:
    description: Устанавливать обновления
    default: op
  scriptcommands.use.*:
    description: Использование динамических команд
    default: true
